# Generated by Django 3.1.8 on 2021-05-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservaHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva_hora', models.IntegerField()),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
    ]
