# Generated by Django 3.1.8 on 2021-05-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_auto_20210509_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservahora',
            old_name='id_reserva_hora',
            new_name='id_cliente',
        ),
        migrations.AlterField(
            model_name='reservahora',
            name='hora_reserva',
            field=models.CharField(max_length=5),
        ),
    ]
