# Generated by Django 3.1.8 on 2021-05-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_auto_20210517_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.CharField(default='', max_length=20),
        ),
    ]
