# Generated by Django 3.1.8 on 2021-05-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0008_auto_20210522_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_usuario',
            field=models.IntegerField(),
        ),
    ]
