# Generated by Django 3.1.8 on 2021-05-22 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0009_auto_20210522_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='vehiculo_marca',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vehiculo_modelo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vehiculo_patente',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reservahora',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reservahora',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registro.cliente'),
        ),
    ]
