# Generated by Django 3.1.8 on 2021-05-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0012_reservahora_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('garantia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('tiempo_ejecucion', models.DurationField()),
                ('estado', models.CharField(max_length=1)),
                ('descuento', models.IntegerField()),
            ],
        ),
    ]
