# Generated by Django 3.1.8 on 2021-06-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0013_producto_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='garantia',
            field=models.IntegerField(),
        ),
    ]
